{% set name = "lstchain" %}
{% set version = "0.10.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lstchain-{{ version }}.tar.gz
  sha256: d5170054ebf452a5af49cdd97cc0a1f576627876f730206889a454056976af89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - lstchain_create_run_summary = lstchain.scripts.lstchain_create_run_summary:main
    - lstchain_mc_r0_to_dl1 = lstchain.scripts.lstchain_mc_r0_to_dl1:main
    - lstchain_convert_drs4_pedestal_to_evb = lstchain.scripts.lstchain_convert_drs4_pedestal_to_evb:main
    - lstchain_significance_calculation = lstchain.scripts.lstchain_significance_calculation:main
    - lstchain_dl1ab = lstchain.scripts.lstchain_dl1ab:main
    - lstchain_mc_sensitivity = lstchain.scripts.lstchain_mc_sensitivity:main
    - lstchain_add_source_dependent_parameters = lstchain.scripts.lstchain_add_source_dependent_parameters:main
    - lstchain_dl1_to_dl2 = lstchain.scripts.lstchain_dl1_to_dl2:main
    - lstchain_data_create_time_calibration_file = lstchain.scripts.lstchain_data_create_time_calibration_file:main
    - lstchain_dump_config = lstchain.scripts.lstchain_dump_config:main
    - lstchain_mc_rfperformance = lstchain.scripts.lstchain_mc_rfperformance:main
    - lstchain_find_pedestals = lstchain.scripts.lstchain_find_pedestals:main
    - lstchain_longterm_dl1_check = lstchain.scripts.lstchain_longterm_dl1_check:main
    - lstchain_merge_hdf5_files = lstchain.scripts.lstchain_merge_hdf5_files:main
    - lstchain_mc_trainpipe = lstchain.scripts.lstchain_mc_trainpipe:main
    - lstchain_merge_muon_files = lstchain.scripts.lstchain_merge_muon_files:main
    - lstchain_tune_nsb = lstchain.scripts.lstchain_tune_nsb:main
    - lstchain_data_r0_to_dl1 = lstchain.scripts.lstchain_data_r0_to_dl1:main
    - lstchain_check_dl1 = lstchain.scripts.lstchain_check_dl1:main
    - lstchain_dvr_pixselector = lstchain.scripts.lstchain_dvr_pixselector:main
    - lstchain_mc_r0_to_dl2 = lstchain.scripts.lstchain_mc_r0_to_dl2:main
    - lstchain_dl1_muon_analysis = lstchain.scripts.lstchain_dl1_muon_analysis:main
    - onsite_create_drs4_pedestal_file = lstchain.scripts.onsite.onsite_create_drs4_pedestal_file:main
    - onsite_create_calibration_files_with_batch = lstchain.scripts.onsite.onsite_create_calibration_files_with_batch:main
    - onsite_create_ffactor_systematics_file = lstchain.scripts.onsite.onsite_create_ffactor_systematics_file:main
    - onsite_create_calibration_file = lstchain.scripts.onsite.onsite_create_calibration_file:main
    - onsite_create_drs4_time_file = lstchain.scripts.onsite.onsite_create_drs4_time_file:main
    - lstchain_create_drs4_pedestal_file = lstchain.tools.lstchain_create_drs4_pedestal_file:main
    - lstchain_create_irf_files = lstchain.tools.lstchain_create_irf_files:main
    - lstchain_create_dl3_file = lstchain.tools.lstchain_create_dl3_file:main
    - lstchain_create_cat_B_calibration_file = lstchain.tools.lstchain_create_cat_B_calibration_file:main
    - lstchain_create_calibration_file = lstchain.tools.lstchain_create_calibration_file:main
    - lstchain_fit_intensity_scan = lstchain.tools.lstchain_fit_intensity_scan:main
    - lstchain_create_dl3_index_files = lstchain.tools.lstchain_create_dl3_index_files:main

requirements:
  host:
    - python >=3.9
    - setuptools >=40.6.0
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.9
    - astropy >=5.0,<6.dev0
    - bokeh >=2.0,<3.dev0
    - ctapipe >=0.19.2,<0.20.dev0
    - ctapipe_io_lst >=0.23.0,<0.24.dev0
    - ctaplot >=0.6.4,<0.7.dev0
    - eventio >=1.9.1,<2.0.0a0
    - gammapy >=1.1,<2.dev0
    - h5py
    - iminuit >=2
    - joblib >=1.2.0,<1.3.dev0
    - matplotlib-base >=3.7,<3.8.0dev0
    - numba
    - numpy
    - pandas
    - pyirf >=0.10.0,<0.11.0dev0
    - scipy >=1.8,<1.12
    - seaborn
    - scikit-learn >=1.2,<2.dev0
    - pytables
    - toml
    - pymongo
    - pyparsing
    - protozfits >=2.5,<3.dev0

test:
  imports:
    - lstchain
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/cta-lstchain
  summary: Analysis chain for the CTA-LST prototype
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rlopezcoto
    - moralejo
    - maxnoe
